version: "3.8"

volumes:
  accounts_db_data:

services:
  accounts_db:
    image: postgres:16.4-alpine
    container_name: accounts_db
    ports:
      - 15432:5432
    volumes:
      - accounts_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
