server:
  port: 8081
spring:
  application:
    name: accounts
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:15432/postgres}
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    database: POSTGRESQL
springdoc:
  show-actuator: true
