spring:
    application:
        name: accounts
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
    docker:
        compose:
            stop:
                command: down
