spring:
    application:
        name: accounts
    datasource:
      url: jdbc:postgresql://localhost:15432/postgres
      username: postgres
      password: postgres
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
        database: POSTGRESQL
    docker:
        compose:
            stop:
                command: down
