spring:
  application.name: accounts
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:15432/postgres}
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate.ddl-auto: none
    database: POSTGRESQL
symida:
  accounts:
    jwt:
      cookieName: symida
      secret: aVeryLongSecretKeyThatIsAtLeast32Characters
      expirationMs: 30000
springdoc:
  show-actuator: true